# Generated by Django 3.2.12 on 2022-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20220429_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
